# TensorFlow 
## TensorFlow Eager API Basics
### by [Sameer Kumar](https://sites.google.com/view/bvsk35/home?authuser=0)

### What is Eager API?
TensorFlow's eager execution is an imperative programming environment that evaluates operations immediately, without building graphs: operations return concrete values instead of constructing a computational graph to run later. This makes it easy to get started with TensorFlow and debug models, and it reduces boilerplate as well. Eager execution is a flexible machine learning platform for research and experimentation, providing:
- An intuitive interface: Structure your code naturally and use Python data structures. Quickly iterate on small models and small data.
- Easier debugging: Call ops directly to inspect running models and test changes. Use standard Python debugging tools for immediate error reporting.
- Natural control flow: Use Python control flow instead of graph control flow, simplifying the specification of dynamic models.

More detailed explanation for this can be found [here](https://ai.googleblog.com/2017/10/eager-execution-imperative-define-by.html) and [here](https://www.tensorflow.org/guide/eager). Its effectivness has been enhanced in the newer tensorflow version tf-2.0 and about this you can read it [here](https://www.tensorflow.org/beta/guide/effective_tf2).

In [1]:
# Import required Libraries
import tensorflow as tf
import numpy as np

In [2]:
# Set Eager API mode
print('Setting Eager API mode....')
tf.enable_eager_execution()
if tf.executing_eagerly():
    print('Eager Execution has been enabled')
else:
    print('FAILED!!!')

Setting Eager API mode....
Eager Execution has been enabled


In [3]:
# Define Constant tensors
print('Define constant tensors')
a = tf.constant(2.0)
print('a = {0:.1f}'.format(a))
b = tf.constant(3.0)
print('b = {0:.1f}'.format(b))

Define constant tensors
a = 2.0
b = 3.0


In [4]:
# Note we can run opertaion without calling tf.sessions
# Operator overloading is supported: +, -, * etc
print('Doing computations without calling tf.sessions')
c = a + b
print('a + b = c = {0:.1f}'.format(c))
d = a * b
print('a * b = d = {0:.1f}'.format(d))

Doing computations without calling tf.sessions
a + b = c = 5.0
a * b = d = 6.0


### Note:
Enabling eager execution changes how TensorFlow operations behave. Now they immediately evaluate and return their values to Python. `tf.Tensor` objects reference concrete values instead of symbolic handles to nodes in a computational graph. Since there isn't a computational graph to build and run later in a session, it's easy to inspect results using `print()` or a debugger. Evaluating, printing, and checking tensor values does not break the flow for computing gradients.

Eager execution works nicely with NumPy. NumPy operations accept `tf.Tensor` arguments. TensorFlow [math operations](https://www.tensorflow.org/api_docs/python/tf/math) convert Python objects and NumPy arrays to `tf.Tensor` objects. The `tf.Tensor.numpy` method returns the object's value as a NumPy `ndarray`.

In [5]:
print('All the variables used till now are tf.tensor objects.')
print('a = ', a)
print('b = ', b)
print('c = ', c)
print('d = ', d)

All the variables used till now are tf.tensor objects.
a =  tf.Tensor(2.0, shape=(), dtype=float32)
b =  tf.Tensor(3.0, shape=(), dtype=float32)
c =  tf.Tensor(5.0, shape=(), dtype=float32)
d =  tf.Tensor(6.0, shape=(), dtype=float32)


In [6]:
# Compatibility with Numpy
# Numpy arrays and Tensorflow objects can be combined for computations
# as explained in the above note
a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
print('TensorFlow tf.Tensor object: \n a = ', a)
b = np.array([[5, 6], [7, 8]], dtype=np.float32)
print('Numpy ndarray: \n b = ', b)

TensorFlow tf.Tensor object: 
 a =  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Numpy ndarray: 
 b =  [[5. 6.]
 [7. 8.]]


In [7]:
# Numpy ndarray will be converted to tf.Tensor object
print('Doing computations without calling tf.sessions')
c = a + b
print('a + b = c = \n {0}'.format(c))
d = tf.matmul(a, b)
print('a * b = d = \n {0}'.format(d))

Doing computations without calling tf.sessions
a + b = c = 
 [[ 6.  8.]
 [10. 12.]]
a * b = d = 
 [[19. 22.]
 [43. 50.]]


In [8]:
print('Iterating through tensor "a" :')
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

Iterating through tensor "a" :
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)


In [9]:
print('All the variables used till now are tf.tensor objects.')
print('a = ', a)
print('b = ', b)
print('c = ', c)
print('d = ', d)

All the variables used till now are tf.tensor objects.
a =  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
b =  [[5. 6.]
 [7. 8.]]
c =  tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
d =  tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [10]:
# As explained in the note we can pass tf.Tensor objects as arguments to 
# Numpy hence it works other way around also. 
e = np.matmul(a, b)
print('a * b = e = \n {0}'.format(e))
print('Note: "e" is numpy array now.')

a * b = e = 
 [[19. 22.]
 [43. 50.]]
Note: "e" is numpy array now.


In [11]:
# Finally there is a easy way to convert tf.Tensor objects into Numpy arrays
# Obtain numpy value from a tensor:
a = a.numpy()
print('a = ', a)

a =  [[1. 2.]
 [3. 4.]]


The tf.contrib.eager module contains symbols available to both eager and graph execution environments and is useful for writing code to work with graphs: `tfe = tf.contrib.eager`. For more on this please refer to the links provided above.